openapi: 3.0.0
info:
  title: ACT.cloud webhook API
  description: ACT cloud sensor data post API.
  version: 0.1.0
servers:
  - url: https://hooks.act-node.com/service/v1
    description: ACT cloud webhook APIs
paths:
  /{groupCode}/{Key}:
    post:
      summary: post sensor data.
      description: sensor data send to ACT.cloud.
      parameters:
      - in: path
        name: "groupCode"
        required: true
        schema:
          type: string
          description: Group groupCode
      - in: path
        name: Key
        required: true
        schema:
          type: string
          description: Whebhook Key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - value
              properties:
                type:
                  type: string
                name:
                  type: string
                value:
                  type: number
                unit:
                  type: string
                time:
                  type: string
                  format: date-time
                location:
                  type: object
                  required:
                    - lat
                    - lng
                  properties:
                    lat:
                      type: string
                    lng:
                      type: string
              example:
                type: env
                name: temp
                value: 23.4
                unit: ℃
                time: 2021-01-10T09:12:34.56789Z
                location: {lat: 35.391133800000006, lng: 139.55841339999998}
      responses:
        '200':
          description: Successfully post sensor data
          content:
            application/json:
              schema:
                type: object
                properties:   
                  type:
                    type: string
                  name:
                    type: string
                  value:
                    type: number
                  unit:
                    type: string
                  time: 
                    type: string
                    format: date-time
                  location:
                    type: object
                    properties:
                      lat:
                        type: string
                      lng:
                        type: string
        '400':
          description: Bad Request. Incorect request.
        '403':
          description: Forbidden. webhook URL NOT exist or expired

  /dcmhka/{groupCode}/{key}:
    post:
      summary: post Docomo Hatake Assist sensor data.
      description: post Docomo Hatake Assist sensor data send to ACT.cloud.
      parameters:
      - in: path
        name: "groupCode"
        required: true
        schema:
          type: string
          description: Group groupCode
      - in: path
        name: Key
        required: true
        schema:
          type: string
          description: Whebhook Key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - type
                - info
              properties:
                type:
                  type: string
                info:
                  type: object
                  required:
                    - device
                    - time
                  properties:
                    device:
                      type: string
                    time:
                      type: integer
                      description: UNIX Time
                data:
                  type: array
              example:
                type: sensor_data
                info: { device: 11130231756A0021, time: 1550647733}
                data: [ { masterPort: 1, expandPort: 5, name: ph, value: 9.71}, { masterPort: 1, expandPort: 4, name: water_do, value: 13.89}]
      responses:
        '200':
          description: Successfully post sensor data
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
        '400':
          description: Bad Request. Incorect request.
        '403':
          description: Forbidden. webhook URL NOT exist or expired