openapi: 3.0.0
info:
  title: ACT.cloud webhook API
  description: ACT cloud sensor data post API.
  version: 0.1.0
servers:
  - url: https://hooks.act-node.com/service/v1
    description: ACT cloud webhook APIs
paths:
  /{group_code}/{key}:
    post:
      summary: post sensor data.
      description: sensor data send to ACT.cloud.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - value
              properties:
                type:
                  type: string
                name:
                  type: string
                value:
                  type: number
                unit:
                  type: string
                time:
                  type: string
                location:
                  type: object

      responses:
        '200':
          description: Successfully post sensor data
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string