openapi: 3.0.0
info:
  title: ACT.cloud webhook API
  description: ACT cloud sensor data post API.
  version: 0.1.0
servers:
  - url: https://hooks.act-node.com/service/v1
    description: ACT cloud webhook APIs
paths:
  /{group_code}/{key}:
    post:
      summary: post sensor data.
      description: sensor data send to ACT.cloud.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string